# Site settings
title: "ì—¬ëŸ¬ê°€ì§€ ì‹¤í—˜ê³¼ ìƒê° ëª¨ìŒ"
description: > 
  gaeekim laboratory ðŸ‘€

author: gaee kim
email: gaeekim@gmail.com
# twitter_username: _HairForceOne
instagram_username: gaeekim

baseurl: "/gaeekim" # the subpath of your site, e.g. /blog
url: "https://gaeekim.github.io/gaeekim/" # the base hostname & protocol for your site

google_analytics_id: 
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

